### ISSUE TITLE
Tests fail on Perl 5.24 due to unmet List::Util version dependency

### ISSUE THREAD

**Issue by esproul** [houseabsolute/DateTime-Locale#12]
I'm attempting to `make test` under Perl 5.24 but getting this warning:

```
# *** WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING ***
#
# The following REQUIRED prerequisites were not satisfied:
#
# List::Util version '1.42_02' is not in required range '1.45'
```

5.24 is the latest stable version of perl, so could the List::Util version dependency be relaxed a bit?

**Comment by preaction** [comment]
It looks to me like DateTime::Locale needs List::Util 1.45 specifically, since it uses List::Util's `uniq` function (https://github.com/houseabsolute/DateTime-Locale/blob/9fdd399cb18ea6bd739a59e26f13ab9a8d7332f3/lib/DateTime/Locale/Base.pm#L97-L99) which is fixed to work without strangeness in List::Util 1.45 (https://metacpan.org/changes/distribution/Scalar-List-Utils#L19-23)

**Comment by autarch** [comment]
Yes, that is probably why that was done.
